// @generated by scripts/gen-plugin-catalog.mjs from apps/desktop/src-tauri/src/config.rs
// DO NOT EDIT BY HAND. Add a plugin by adding a `KNOWN_PLUGINS` row in config.rs and re-running
// the generator; every TypeScript key list is derived from this array (see ./pluginCatalog.ts).

/** One catalog row, mirroring a Rust `KnownPlugin`.
 *
 *  `key` is the frontend's camelCase spelling, `tomlKey` the snake_case `[plugins]` key Rust
 *  reads and writes, `plugin` the plugin's own name inside its marketplace, and `defaultOn`
 *  the shipped default. */
export interface PluginCatalogRow {
  readonly key: string;
  readonly tomlKey: string;
  readonly plugin: string;
  readonly defaultOn: boolean;
}

export const PLUGIN_CATALOG = [
  { key: "superpowers", tomlKey: "superpowers", plugin: "superpowers", defaultOn: true },
  { key: "frontendDesign", tomlKey: "frontend_design", plugin: "frontend-design", defaultOn: true },
  { key: "hookify", tomlKey: "hookify", plugin: "hookify", defaultOn: true },
  { key: "codeSimplifier", tomlKey: "code_simplifier", plugin: "code-simplifier", defaultOn: true },
  { key: "sparkleGuardrails", tomlKey: "sparkle_guardrails", plugin: "sparkle-guardrails", defaultOn: false },
  { key: "sparkleFreshness", tomlKey: "sparkle_freshness", plugin: "sparkle-freshness", defaultOn: true },
  { key: "sparkleMutationCheck", tomlKey: "sparkle_mutation_check", plugin: "sparkle-mutation-check", defaultOn: false },
  { key: "sparkleConflictWatch", tomlKey: "sparkle_conflict_watch", plugin: "sparkle-conflict-watch", defaultOn: false },
  { key: "sparkleSecrets", tomlKey: "sparkle_secrets", plugin: "sparkle-secrets", defaultOn: false },
  { key: "sparkleReviewProbes", tomlKey: "sparkle_review_probes", plugin: "sparkle-review-probes", defaultOn: false },
  { key: "sparklePusher", tomlKey: "sparkle_pusher", plugin: "sparkle-pusher", defaultOn: false },
  { key: "elementsOfStyle", tomlKey: "elements_of_style", plugin: "elements-of-style", defaultOn: true },
  { key: "doubleShotLatte", tomlKey: "double_shot_latte", plugin: "double-shot-latte", defaultOn: true },
  { key: "compoundEngineering", tomlKey: "compound_engineering", plugin: "compound-engineering", defaultOn: true },
  { key: "differentialReview", tomlKey: "differential_review", plugin: "differential-review", defaultOn: true },
  { key: "reviewSquad", tomlKey: "review_squad", plugin: "review-squad", defaultOn: true },
] as const satisfies readonly PluginCatalogRow[];
