// The READ half of the durable orchestrator binding (bead `sparkle-n2feho.9`).
//
// The end-to-end acceptance — a real handoff, a real `projectStore.removeAgent`, and the binding
// still recoverable — lives in `durableBinding.fleetRefresh.test.ts`. THIS file is the unit level:
// the parser's two arms and their precedence, and the reader's live-wins-and-reads-nothing rule.
import { describe, it, expect, vi } from "vitest";
import {
  BINDING_TRAILER_TAG,
  handoffRecordComment,
  parseHandoffRecord,
  resolveOrchestratorBinding,
  type DurableBindingDeps,
} from "./durableBinding";
import type { BeadComment } from "./beadsCommands";

let seq = 0;
/** A comment carrying arbitrary text. The FIXTURE VARIES EVERY FIELD UNDER TEST — text, order and
 *  count are all parameters — because a fixture that hardcodes one comment shape cannot express a
 *  re-handoff, a malformed record, or a thread of ordinary human conversation (AGENTS.md). */
function comment(text: string, over: Partial<BeadComment> = {}): BeadComment {
  return {
    id: `c${++seq}`,
    author: "DROdio",
    text,
    createdAt: "2026-09-04T00:00:00Z",
    ...over,
  };
}

/**
 * THE PRE-TRAILER RECORD, verbatim as `sparkle-n2feho.8` shipped it and as every record already on
 * `origin/main` is written.
 *
 * Spelled out here as a LITERAL rather than derived from `handoffRecordComment`, deliberately: the
 * point of the fallback arm is that it reads text this codebase no longer produces, so a fixture
 * generated by today's writer could not prove it. If someone reformats the writer, this string must
 * stay exactly as it is — it is a fact about history, not about the current code.
 */
function proseOnly(agentId: string, projectId: string): string {
  return (
    `Handed to Build: orchestrator \`${agentId}\` in project \`${projectId}\`. ` +
    `Recorded here because the binding itself (AgentTab.epicId) lives only in this window's ` +
    `local store — this comment is what survives a fleet refresh (bead sparkle-n2feho.8).`
  );
}

/** A trailer line with an arbitrary payload — so a test can build a MALFORMED one, which the
 *  writer by construction cannot. */
function trailerLine(payload: string): string {
  return `${BINDING_TRAILER_TAG} ${payload}`;
}

describe("handoffRecordComment — one formatter, both encodings", () => {
  it("round-trips: what the writer emits parses back to the SAME pair, via the trailer", () => {
    const text = handoffRecordComment({
      agentId: "build-7",
      projectId: "proj-alpha",
      beadId: "e1.t3",
      at: 1_788_000_000_000,
    });
    expect(parseHandoffRecord([comment(text)])).toEqual({
      agentId: "build-7",
      projectId: "proj-alpha",
      beadId: "e1.t3",
      at: 1_788_000_000_000,
      encoding: "trailer",
    });
  });

  it("carries the HUMAN sentence as well as the machine record, naming the same pair", () => {
    const text = handoffRecordComment({
      agentId: "build-9",
      projectId: "proj-beta",
      beadId: "b1",
      at: 5,
    });
    // The prose half, asserted independently of the parser: a reader in the bd thread must still be
    // told what happened in words. Stripping the trailer proves the sentence stands on its own —
    // and that BOTH halves name the same agent and project, which is the whole reason one function
    // emits them.
    const withoutTrailer = text
      .split("\n")
      .filter((l) => !l.startsWith(BINDING_TRAILER_TAG))
      .join("\n");
    expect(withoutTrailer).toContain("Handed to Build: orchestrator `build-9` in project `proj-beta`");
    expect(parseHandoffRecord([comment(withoutTrailer)])).toMatchObject({
      agentId: "build-9",
      projectId: "proj-beta",
      encoding: "prose",
    });
  });

  it("keeps the trailer on ONE line even when an id contains a newline", () => {
    const text = handoffRecordComment({
      agentId: "build\n1",
      projectId: "p\n2",
      beadId: "b",
      at: 1,
    });
    const trailers = text.split("\n").filter((l) => l.startsWith(BINDING_TRAILER_TAG));
    expect(trailers).toHaveLength(1);
    // JSON.stringify escapes the newline, so the payload survives the per-line scan intact.
    expect(parseHandoffRecord([comment(text)])).toMatchObject({
      agentId: "build\n1",
      projectId: "p\n2",
      encoding: "trailer",
    });
  });
});

describe("parseHandoffRecord — the trailer arm", () => {
  it("reads a record whose PROSE was reworded — the arm that makes a reword survivable", () => {
    const text = [
      "Some future author rewrote this sentence entirely and mentioned no orchestrator at all.",
      "",
      trailerLine(
        JSON.stringify({ agentId: "build-42", projectId: "proj-x", beadId: "t9", at: 77 }),
      ),
    ].join("\n");
    expect(parseHandoffRecord([comment(text)])).toEqual({
      agentId: "build-42",
      projectId: "proj-x",
      beadId: "t9",
      at: 77,
      encoding: "trailer",
    });
  });

  it("answers when the id contains a BACKTICK, which the prose arm cannot express", () => {
    const text = handoffRecordComment({
      agentId: "build-`odd`",
      projectId: "proj-y",
      beadId: "t1",
      at: 3,
    });
    expect(parseHandoffRecord([comment(text)])).toMatchObject({
      agentId: "build-`odd`",
      encoding: "trailer",
    });
  });
});

describe("parseHandoffRecord — PRECEDENCE, the two rules that are different questions", () => {
  // RULE 2 — within ONE comment, the trailer outranks the prose. Pinned with the two halves naming
  // DIFFERENT agents, which is the only fixture that can tell the arms apart: with matching values
  // both orders pass and the assertion proves nothing.
  it("prefers the TRAILER over the prose when the two disagree", () => {
    const text = [proseOnly("prose-agent", "prose-project"), "", trailerLine(
      JSON.stringify({ agentId: "trailer-agent", projectId: "trailer-project", beadId: "b", at: 1 }),
    )].join("\n");
    const got = parseHandoffRecord([comment(text)]);
    expect(got).toMatchObject({
      agentId: "trailer-agent",
      projectId: "trailer-project",
      encoding: "trailer",
    });
    // Stated as its own assertion: the losing arm's value must be ABSENT, not merely not-first.
    expect(got?.agentId).not.toBe("prose-agent");
  });

  it("falls back to the prose in the SAME comment when the trailer is malformed", () => {
    const text = [
      proseOnly("prose-agent", "prose-project"),
      "",
      trailerLine('{"agentId":"trunc'),
    ].join("\n");
    expect(parseHandoffRecord([comment(text)])).toMatchObject({
      agentId: "prose-agent",
      projectId: "prose-project",
      encoding: "prose",
    });
  });

  // RULE 1 — across comments, the NEWEST wins. `BeadDetail.comments` is oldest-first.
  it("takes the NEWEST record when a bead was re-handed off", () => {
    const thread = [
      comment(handoffRecordComment({ agentId: "build-1", projectId: "p1", beadId: "b", at: 10 })),
      comment("A human replies in the middle of the thread."),
      comment(handoffRecordComment({ agentId: "build-2", projectId: "p2", beadId: "b", at: 20 })),
    ];
    expect(parseHandoffRecord(thread)).toMatchObject({ agentId: "build-2", projectId: "p2" });
  });

  it("a newer PROSE-ONLY record still outranks an older trailer — recency is the outer rule", () => {
    const thread = [
      comment(handoffRecordComment({ agentId: "build-old", projectId: "p-old", beadId: "b", at: 1 })),
      comment(proseOnly("build-new", "p-new")),
    ];
    expect(parseHandoffRecord(thread)).toMatchObject({
      agentId: "build-new",
      encoding: "prose",
    });
  });
});

describe("parseHandoffRecord — THE FALLBACK ARM IS LIVE (every record on origin/main is prose-only)", () => {
  it("recovers a binding from a thread carrying ONLY the pre-trailer form", () => {
    const thread = [
      comment("Filed by hand."),
      comment(proseOnly("build-legacy", "proj-legacy")),
    ];
    expect(parseHandoffRecord(thread)).toEqual({
      agentId: "build-legacy",
      projectId: "proj-legacy",
      beadId: null,
      at: null,
      encoding: "prose",
    });
  });

  it("reports beadId and at as NULL rather than inventing them from the comment's own metadata", () => {
    const got = parseHandoffRecord([
      comment(proseOnly("a", "b"), { createdAt: "2026-01-01T00:00:00Z" }),
    ]);
    expect(got?.beadId).toBeNull();
    expect(got?.at).toBeNull();
  });
});

describe("parseHandoffRecord — malformed input returns null and NEVER throws", () => {
  const cases: Array<[string, string]> = [
    ["an empty thread entry", ""],
    ["ordinary human conversation", "Looks good to me, shipping this."],
    ["a truncated trailer", trailerLine('{"agentId":"a","projectId"')],
    ["a trailer whose payload is not JSON", trailerLine("not json at all")],
    ["a trailer whose payload is an array", trailerLine('["a","b"]')],
    ["a trailer whose payload is a bare string", trailerLine('"just-a-string"')],
    ["a trailer whose payload is null", trailerLine("null")],
    ["a trailer missing agentId", trailerLine('{"projectId":"p"}')],
    ["a trailer missing projectId", trailerLine('{"agentId":"a"}')],
    ["a trailer with a blank agentId", trailerLine('{"agentId":"   ","projectId":"p"}')],
    ["a trailer with a non-string agentId", trailerLine('{"agentId":7,"projectId":"p"}')],
    ["the tag with no payload at all", BINDING_TRAILER_TAG],
    ["prose with an empty agent id", "Handed to Build: orchestrator `` in project `p`."],
  ];
  for (const [label, text] of cases) {
    it(`returns null for ${label}`, () => {
      expect(() => parseHandoffRecord([comment(text)])).not.toThrow();
      expect(parseHandoffRecord([comment(text)])).toBeNull();
    });
  }

  it("returns null for an empty thread", () => {
    expect(parseHandoffRecord([])).toBeNull();
  });

  it("keeps a GOOD record that sits behind a malformed one in the same thread", () => {
    const thread = [
      comment(handoffRecordComment({ agentId: "build-3", projectId: "p3", beadId: "b", at: 9 })),
      comment(trailerLine('{"agentId":"trunc')),
    ];
    expect(parseHandoffRecord(thread)).toMatchObject({ agentId: "build-3" });
  });

  it("drops a non-finite `at` rather than carrying NaN into a caller", () => {
    const got = parseHandoffRecord([
      comment(trailerLine('{"agentId":"a","projectId":"p","at":"soon"}')),
    ]);
    expect(got).toMatchObject({ agentId: "a", at: null });
  });
});

// ---------------------------------------------------------------------------------------------
// The reader
// ---------------------------------------------------------------------------------------------

function depsReturning(thread: BeadComment[]): DurableBindingDeps & { readComments: ReturnType<typeof vi.fn> } {
  const readComments = vi.fn(async () => thread);
  return { readComments } as never;
}

const RECORD = handoffRecordComment({
  agentId: "build-durable",
  projectId: "proj-durable",
  beadId: "e1.t1",
  at: 1_788_000_000_000,
});

describe("resolveOrchestratorBinding — LIVE STRICTLY OUTRANKS DURABLE", () => {
  it("reports source:'live' when a roster row exists, EVEN WITH a durable record present", () => {
    const deps = depsReturning([comment(RECORD)]);
    return resolveOrchestratorBinding(
      {
        projectPath: "/repo",
        beadId: "e1.t1",
        live: { id: "build-live", name: "Live Orchestrator" },
        handedToBuild: true,
      },
      deps,
    ).then((got) => {
      expect(got).toEqual({ source: "live", agentId: "build-live", name: "Live Orchestrator" });
      // THE COST HALF OF THE SAME RULE, asserted separately: live wins BEFORE the read, so the
      // contended detail call never happens. A mutant that reorders the two would still return a
      // live-looking answer here; only this assertion catches it.
      expect(deps.readComments).not.toHaveBeenCalled();
    });
  });

  it("recovers source:'durable' when the row is gone and the bead carries the record", async () => {
    const deps = depsReturning([comment(RECORD)]);
    const got = await resolveOrchestratorBinding(
      { projectPath: "/repo", beadId: "e1.t1", live: null, handedToBuild: true },
      deps,
    );
    expect(got).toEqual({
      source: "durable",
      agentId: "build-durable",
      projectId: "proj-durable",
      at: 1_788_000_000_000,
    });
    expect(deps.readComments).toHaveBeenCalledWith("/repo", "e1.t1");
  });

  // THE PAIRED NEGATIVE. Recovery alone is ambiguous — absence passes for a fixed and an unfixed
  // reader alike — so the two are asserted together.
  it("acquires NO binding for a bead that was never handed to Build, and spends no read", async () => {
    const deps = depsReturning([comment(RECORD)]);
    const got = await resolveOrchestratorBinding(
      { projectPath: "/repo", beadId: "e1.t2", live: null, handedToBuild: false },
      deps,
    );
    expect(got).toBeNull();
    expect(deps.readComments).not.toHaveBeenCalled();
  });

  it("is null for a labelled bead whose thread holds no handoff record", async () => {
    const deps = depsReturning([comment("Just a human note.")]);
    expect(
      await resolveOrchestratorBinding(
        { projectPath: "/repo", beadId: "e1.t3", live: null, handedToBuild: true },
        deps,
      ),
    ).toBeNull();
  });

  it("swallows a failed read rather than rejecting into the caller's plan read", async () => {
    const readComments = vi.fn(async () => {
      throw new Error("bd is locked");
    });
    await expect(
      resolveOrchestratorBinding(
        { projectPath: "/repo", beadId: "e1.t4", live: null, handedToBuild: true },
        { readComments } as never,
      ),
    ).resolves.toBeNull();
  });

  it("recovers from a PROSE-ONLY thread — the records already on origin/main", async () => {
    const deps = depsReturning([comment(proseOnly("build-legacy", "proj-legacy"))]);
    expect(
      await resolveOrchestratorBinding(
        { projectPath: "/repo", beadId: "e1.t5", live: null, handedToBuild: true },
        deps,
      ),
    ).toEqual({
      source: "durable",
      agentId: "build-legacy",
      projectId: "proj-legacy",
      at: null,
    });
  });
});
